### PR TITLE
bau: publish to bintray/alphagov

### PR DESCRIPTION
**Pull request by richardTowers**
Once this is merged we will need to update the jenkins job for this repo
so it has BINTRAY_USER and BINTRAY_API_KEY set (securely).

This will mean that we can make the next level of libs build on travis
with the perl hack (or similar) in .travis.yml.

Pushing to the `maven-test` instead of the `maven` repo to dissuade
third parties from using these builds, as I don't think we'd want to
support them.

### CODE REVIEW

**Comment by richardTowers** [comment]
To be clear - this won't break the jenkins job because it doesn't call `bintrayUpload` yet.

**Comment by richardTowers** [comment]
Also - could push this via travis instead of jenkins if we wanted to, but the build numbers would get out of sync and cause confusion. I think it's best to let jenkins :shipit:.

**Comment by richardTowers** [comment]
I think we could do it more elegantly with an environment variable / system property / something. But yeah, if we want to keep private package hosting (a la artifactory) as the hosting for actual hub then I think some kind of hack will need to stay in place.

Might be a discussion to have around just trusting bintray, but that's for Verify to discuss.

**Comment by willp-bl** [comment]
Probably want to do something to set BUILD_NUMBER? like this - https://github.com/alphagov/dropwizard-logstash/blob/298eab65b562cdfad0ba95725ebb0cdb0aa6facd/.travis.yml#L10

If we do something like this then the build numbers will match the build jenkins - 
`echo build_2000 | tr -d 'build_'`

**Comment by richardTowers** [comment]
This doesn't change what's happening on Travis for this repo - it's Jenkins that's publishing to bintray. Since Travis is still basically just running tests I don't think we need to worry about the build number.

In general I don't think it's possible to keep the build numbers in sync without doing something very hacky (e.g. because triggering a build in jenkins manually bumps the version number).

**Comment by willp-bl** [comment]
Ah.  A dropwizard-logstash build & push-to-bintray is triggered by a new tag on the repo, and pushed up from travis.  It's nicer to be directly pushing it up from the build jenkins though.

**Pull request merged**
